# Generated by Django 4.1.6 on 2023-02-14 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
